name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $(date +%s) > hi.txt
      - run: ls -lah
      - run: git config user.email "tushar10141@gmail.com"
      - run: git config user.name "ParaSpl01t"
      - run: git add .
      - run: git commit -m "automatic build"
      - run: git push origin
